### ISSUE TITLE
Review authorization

### ISSUE THREAD

**Issue by mrodrigues95** [mrodrigues95/spout#25]
We currently use `[Authorize]` for some queries and mutations but it does not work as intended since some methods that are not annotated with this still require authentication.

Looks like this is being reviewed here: https://github.com/ChilliCream/hotchocolate/issues/3995

Once a fix for this is pushed, we should verify all queries/mutations/subscriptions that are _**not**_ annotated with `[Authorize]` work as intended.

**Comment by mrodrigues95** [comment]
Looks like if you remove `[Authorize]` from the base class and add it to every query/mutation/subscription, it'll work as intended.

**Comment by neil-119** [comment]
> Looks like if you remove `[Authorize]` from the base class and add it to every query/mutation/subscription, it'll work as intended.

Can you elaborate on this, @mrodrigues95 ? We added `[Authorize]` specifically to certain queries / mutations (each with `ExtendObjectType`) and noticed that it was applying `[Authorize]` globally. The extend behavior when it comes to authorization is very confusing.

Are you saying that we should remove the auth attribute from the class level and apply it to every method within the class instead? Thanks.

**Comment by mrodrigues95** [comment]
@neil-119 Yes, remove `[Authorize]` from the class and only apply it on every method that requires authorization instead.

Given the following example:
```
[Authorize]
[ExtendObjectType(OperationTypeNames.Query)]
public class UserQueries { ... }
```
This would apply authorization on the base query type and therefore affect every query within my schema. By annotating the methods inside that class instead, it would work as intended. This is also the same behavior for mutations and subscriptions.

I only found this out after coming across -> https://github.com/ChilliCream/hotchocolate/issues/3995
